import { EditCampaignFormData } from "@/src/components/ongoing-campaigns/edit/types";

export const MOCK_CAMPAIGN_DATA: EditCampaignFormData = {
  campaignTitle: "Fully Belly Community Garden",
  beneficiaryCount: "250",
  gardenSize: "2000",
  gardenStatus: "existing",
  fundraisingGoal: "3500",
  gardenCity: "Scarborough",
  gardenState: "Maine",
  gardenCountry: "United States",
  gardenCategory: "Community Garden",
  gardenBeneficiaries: ["Children (ages 0-12)", "Families"],
  organizationName: "Full Belly Gardeners Association",
  organizationIdentifier: "12-3456789",
  mailingStreet1: "123 Scarborough Dr",
  mailingStreet2: "",
  mailingCity: "Scarborough",
  mailingState: "Maine",
  mailingZip: "98921",
  mailingCountry: "United States",
  contactFirstName: "Roger",
  contactLastName: "Doiron",
  contactEmail: "rogerdoiron@gmail.cpm",
  contactRole: "Director",
  storyLocationAndAudience:
    "The Full Belly Community Garden in Scarborough, Maine, provide over 300 pounds of produce annually to local food-insecure families and seniors. Beyond its harvest, it serves as an education hub for at-risk youth and neighbors through nature exploration and hands-on workshops.",
  storyLocationAndAudienceAI:
    "The Full Belly Community Garden in Scarborough, Maine, provides over 300 pounds of organic produce annually to local food-insecure families and seniors. Beyond its harvest, it serves as an educational hub for at-risk youth and neighbors through nature exploration and hands-on workshops.",
  storyLocationAndAudienceFinal:
    "The Full Belly Community Garden in Scarborough, Maine, provides over 300 pounds of produce annually to local food-insecure families and seniors. Beyond its harvest, it serves as an educational hub for at-risk youth and neighbors through nature exploration and hands-on gardening workshops.",
  storyChallengeOriginal:
    "The Full Belly Community Garden addresses the challenge of food insecurity, specifically the difficulty many local families and seniors face in accessing fresh, affordable organic produce.",
  storyChallengeAI:
    "The Full Belly Community Garden addresses the challenge of food insecurity, specifically the barriers many local families and seniors face in accessing fresh, affordable produce.",
  storyChallengeFinal:
    "The Full Belly Community Garden addresses the challenge of food insecurity, specifically the difficulty many local families and seniors face in accessing fresh, affordable organic produce.",
  storySeasonActivityOriginal:
    "During the growing season, it serves as a 'vibrant oasis' where volunteers host monthly workshops to teach gardening skills and provide a safe space for at-risk youth to explore nature.",
  storySeasonActivityAI:
    "During the growing season, the garden becomes a vibrant community space where volunteers lead monthly workshops, teach practical gardening skills, and provide a safe place for at-risk youth to connect with nature.",
  storySeasonActivityFinal:
    "During the growing season, it serves as a 'vibrant oasis' where volunteers host monthly workshops to teach gardening skills and provide a safe space for at-risk youth to explore nature.",
  storyCampaignImpactOriginal:
    "These contributions allow the garden to continue its mission of providing over 300 pounds of organic food to local food-insecure families and seniors at the Elm Street Senior Center.",
  storyCampaignImpactAI:
    "These contributions enable the garden to continue providing more than 300 pounds of organic food to local food-insecure families and seniors at the Elm Street Senior Center.",
  storyCampaignImpactFinal:
    "These contributions allow the garden to continue its mission of providing over 300 pounds of organic food to local food-insecure families and seniors at the Elm Street Senior Center.",
};

export const categoryOptions = [
  "Community Garden",
  "School or Youth Garden",
  "Food Pantry or Food Bank Garden",
  "Urban Farm",
  "Refugee or Immigrant Garden",
  "Tribal or Indigenous Garden Project",
  "Shelter or Transitional Housing Garden",
  "Therapeutic or Healing Garden",
  "Job Training or Vocational Garden",
  "Demonstration or Education Garden",
  "Multi-Site Garden Program",
  "Other (please specify)",
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "India",
  "Germany",
  "France",
  "Japan",
  "Mexico",
];

export const beneficiaryOptions = [
  "Children (ages 0-12)",
  "Youth / Adolescents (ages 13-18)",
  "Families",
  "Seniors / Older adults",
  "Low-income individuals or households",
  "Food-insecure individuals or households",
  "Immigrants and refugees",
  "Indigenous / Native communities",
  "People with disabilities",
  "Veterans and military families",
  "People experiencing homelessness or housing insecurity",
  "Unemployed or underemployed individuals",
  "Justice-involved individuals",
  "Rural communities",
  "Urban communities",
  "Other (please specify)",
];
