import type { Campaign } from "@/src/types/db/campaigns";

export const sampleCampaigns: Campaign[] = [
  {
    campaign_id: 1,
    name: "Save the Ocean Campaign",
    givebutterlink: "https://givebutter.com/save-the-ocean",
    status: "in_progress",
    date_created: "2025-01-15",
    street: "123 Ocean Ave",
    city: "Santa Monica",
    state: "CA",
    country: "US",
    zipcode: "90401",
    project_category: "Environment",
    project_beneficiaries: ["Marine life", "Coastal communities"],
    existence: "existing",
    impact: 500,
    size: 10,
    goal: 50000,
    ein: "12-3456789",
    mailing_street: "123 Ocean Ave",
    mailing_city: "Santa Monica",
    mailing_state: "CA",
    mailing_country: "US",
    mailing_zipcode: "90401",
  },
  {
    campaign_id: 2,
    name: "Community Garden Project",
    givebutterlink: "https://givebutter.com/community-garden",
    status: "submitted_under_review",
    date_created: "2025-03-10",
    street: "456 Green St",
    city: "Portland",
    state: "OR",
    country: "US",
    zipcode: "97201",
    project_category: "Community",
    project_beneficiaries: ["Local residents", "Schools"],
    existence: "new",
    impact: 200,
    size: 5,
    goal: 15000,
    ein: "98-7654321",
    mailing_street: "456 Green St",
    mailing_city: "Portland",
    mailing_state: "OR",
    mailing_country: "US",
    mailing_zipcode: "97201",
  },
  {
    campaign_id: 3,
    name: "Save the Garden",
    givebutterlink: "",
    status: "approved",
    date_created: "2025-06-01",
    street: "789 Bloom Rd",
    city: "Austin",
    state: "TX",
    country: "US",
    zipcode: "73301",
    project_category: "Environment",
    project_beneficiaries: ["Urban communities"],
    existence: "existing",
    impact: 100,
    size: 3,
    goal: 10000,
    ein: "11-2233445",
    mailing_street: "789 Bloom Rd",
    mailing_city: "Austin",
    mailing_state: "TX",
    mailing_country: "US",
    mailing_zipcode: "73301",
  },
  {
    campaign_id: 4,
    name: "Protect the Trees",
    givebutterlink: "https://givebutter.com/protect-trees",
    status: "not_approved",
    date_created: "2025-08-20",
    street: "321 Forest Ln",
    city: "Denver",
    state: "CO",
    country: "US",
    zipcode: "80201",
    project_category: "Environment",
    project_beneficiaries: ["Wildlife", "Hikers"],
    existence: "existing",
    impact: 300,
    size: 8,
    goal: 25000,
    ein: "55-6677889",
    mailing_street: "321 Forest Ln",
    mailing_city: "Denver",
    mailing_state: "CO",
    mailing_country: "US",
    mailing_zipcode: "80201",
  },
];

export const getCampaignById = (campaignId: number) => {
  return sampleCampaigns.find(
    (campaign) => campaign.campaign_id === campaignId,
  );
};
