import type { Campaign } from "@/src/types/db/campaigns";

export const sampleCampaigns: Campaign[] = [
  {
    campaign_id: 1,
    name: "Save the Ocean Campaign",
    organization_name: "",
    givebutterlink: "https://givebutter.com/save-the-ocean",
    givebutter_id: null,
    givebutter_slug: null,
    status: "in_progress",
    date_created: "2026-01-15",
    street: "123 Ocean Ave",
    city: "Santa Monica",
    state: "CA",
    country: "US",
    zipcode: "90401",
    project_category: "Environment",
    project_beneficiaries: ["Marine life", "Coastal communities"],
    existence: "existing",
    impact: 500,
    size: "10",
    goal: 50000,
    ein: "12-3456789",
    contact_first_name: "",
    contact_last_name: "",
    contact_email: "",
    contact_role: "",
    mailing_street_1: "123 Ocean Ave",
    mailing_street_2: "",
    mailing_city: "Santa Monica",
    mailing_state: "CA",
    mailing_country: "US",
    mailing_zipcode: "90401",
    raised: 32000,
    donors: 150,
    competition_id: 1,
  },
  {
    campaign_id: 2,
    name: "Community Garden Project",
    organization_name: "",
    givebutterlink: "https://givebutter.com/community-garden",
    givebutter_id: null,
    givebutter_slug: null,
    status: "archived",
    date_created: "2025-03-10",
    street: "456 Green St",
    city: "Portland",
    state: "OR",
    country: "US",
    zipcode: "97201",
    project_category: "Community",
    project_beneficiaries: ["Local residents", "Schools"],
    existence: "new",
    impact: 200,
    size: "5",
    goal: 15000,
    ein: "98-7654321",
    contact_first_name: "",
    contact_last_name: "",
    contact_email: "",
    contact_role: "",
    mailing_street_1: "456 Green St",
    mailing_street_2: "",
    mailing_city: "Portland",
    mailing_state: "OR",
    mailing_country: "US",
    mailing_zipcode: "97201",
    raised: 12500,
    donors: 85,
    competition_id: 1,
  },
  {
    campaign_id: 3,
    name: "Save the Garden",
    organization_name: "",
    givebutterlink: "",
    givebutter_id: null,
    givebutter_slug: null,
    status: "published",
    date_created: "2025-06-01",
    street: "789 Bloom Rd",
    city: "Austin",
    state: "TX",
    country: "US",
    zipcode: "73301",
    project_category: "Environment",
    project_beneficiaries: ["Urban communities"],
    existence: "existing",
    impact: 100,
    size: "3",
    goal: 10000,
    ein: "11-2233445",
    contact_first_name: "",
    contact_last_name: "",
    contact_email: "",
    contact_role: "",
    mailing_street_1: "789 Bloom Rd",
    mailing_street_2: "",
    mailing_city: "Austin",
    mailing_state: "TX",
    mailing_country: "US",
    mailing_zipcode: "73301",
    raised: 6500,
    donors: 45,
    competition_id: 1,
  },
  {
    campaign_id: 4,
    name: "Protect the Trees",
    organization_name: "",
    givebutterlink: "https://givebutter.com/protect-trees",
    givebutter_id: null,
    givebutter_slug: null,
    status: "archived",
    date_created: "2025-08-20",
    street: "321 Forest Ln",
    city: "Denver",
    state: "CO",
    country: "US",
    zipcode: "80201",
    project_category: "Environment",
    project_beneficiaries: ["Wildlife", "Hikers"],
    existence: "existing",
    impact: 300,
    size: "8",
    goal: 25000,
    ein: "55-6677889",
    contact_first_name: "",
    contact_last_name: "",
    contact_email: "",
    contact_role: "",
    mailing_street_1: "321 Forest Ln",
    mailing_street_2: "",
    mailing_city: "Denver",
    mailing_state: "CO",
    mailing_country: "US",
    mailing_zipcode: "80201",
    raised: 18000,
    donors: 120,
    competition_id: 1,
  },
  {
    campaign_id: 5,
    name: "Clean Rivers Initiative",
    organization_name: "",
    givebutterlink: "https://givebutter.com/clean-rivers",
    givebutter_id: null,
    givebutter_slug: null,
    status: "submitted_under_review",
    date_created: "2026-04-12",
    street: "901 River Rd",
    city: "Madison",
    state: "WI",
    country: "US",
    zipcode: "53703",
    project_category: "Environment",
    project_beneficiaries: ["Local communities", "Wildlife"],
    existence: "new",
    impact: 150,
    size: "4",
    goal: 20000,
    ein: "44-5566778",
    contact_first_name: "",
    contact_last_name: "",
    contact_email: "",
    contact_role: "",
    mailing_street_1: "901 River Rd",
    mailing_street_2: "",
    mailing_city: "Madison",
    mailing_state: "WI",
    mailing_country: "US",
    mailing_zipcode: "53703",
    raised: 9500,
    donors: 60,
    competition_id: 1,
  },
];

export const getCampaignById = (campaignId: number) => {
  return sampleCampaigns.find(
    (campaign) => campaign.campaign_id === campaignId,
  );
};
