
  create table "public"."campaign_image_records" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "campaign_id" bigint not null,
    "storage_path" text not null,
    "display_order" bigint not null default 0,
    "is_main" boolean not null default false
      );


alter table "public"."campaigns" drop column "mailing_street";

alter table "public"."campaigns" add column "contact_email" text default ''::text;

alter table "public"."campaigns" add column "contact_first_name" text default ''::text;

alter table "public"."campaigns" add column "contact_last_name" text default ''::text;

alter table "public"."campaigns" add column "contact_role" text default ''::text;

alter table "public"."campaigns" add column "mailing_street_1" text;

alter table "public"."campaigns" add column "mailing_street_2" text default ''::text;

alter table "public"."campaigns" add column "organization_name" text default ''::text;

alter table "public"."competition_metadata" disable row level security;

CREATE UNIQUE INDEX campaign_image_records_pkey ON public.campaign_image_records USING btree (id);

CREATE UNIQUE INDEX campaign_image_records_storage_path_key ON public.campaign_image_records USING btree (storage_path);

CREATE UNIQUE INDEX one_main_image_per_campaign ON public.campaign_image_records USING btree (campaign_id) WHERE (is_main = true);

CREATE UNIQUE INDEX unique_supporting_image_order_per_campaign ON public.campaign_image_records USING btree (campaign_id, display_order) WHERE (is_main = false);

alter table "public"."campaign_image_records" add constraint "campaign_image_records_pkey" PRIMARY KEY using index "campaign_image_records_pkey";

alter table "public"."campaign_image_records" add constraint "campaign_image_records_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES public.campaigns(campaign_id) ON DELETE CASCADE not valid;

alter table "public"."campaign_image_records" validate constraint "campaign_image_records_campaign_id_fkey";

alter table "public"."campaign_image_records" add constraint "campaign_image_records_storage_path_key" UNIQUE using index "campaign_image_records_storage_path_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.users (id, created_at, first_name, middle_name, last_name, email, phone_number, is_admin)
  values (
    new.id,
    new.created_at,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'middle_name',
    new.raw_user_meta_data->>'last_name',
    new.email,
    new.raw_user_meta_data->>'phone_number',
    false
  )
  on conflict (id) do update set
    first_name   = excluded.first_name,
    middle_name  = excluded.middle_name,
    last_name    = excluded.last_name,
    email        = excluded.email,
    phone_number = excluded.phone_number,
    is_admin     = excluded.is_admin;
  
  return new;
end;
$function$
;

grant delete on table "public"."campaign_image_records" to "anon";

grant insert on table "public"."campaign_image_records" to "anon";

grant references on table "public"."campaign_image_records" to "anon";

grant select on table "public"."campaign_image_records" to "anon";

grant trigger on table "public"."campaign_image_records" to "anon";

grant truncate on table "public"."campaign_image_records" to "anon";

grant update on table "public"."campaign_image_records" to "anon";

grant delete on table "public"."campaign_image_records" to "authenticated";

grant insert on table "public"."campaign_image_records" to "authenticated";

grant references on table "public"."campaign_image_records" to "authenticated";

grant select on table "public"."campaign_image_records" to "authenticated";

grant trigger on table "public"."campaign_image_records" to "authenticated";

grant truncate on table "public"."campaign_image_records" to "authenticated";

grant update on table "public"."campaign_image_records" to "authenticated";

grant delete on table "public"."campaign_image_records" to "service_role";

grant insert on table "public"."campaign_image_records" to "service_role";

grant references on table "public"."campaign_image_records" to "service_role";

grant select on table "public"."campaign_image_records" to "service_role";

grant trigger on table "public"."campaign_image_records" to "service_role";

grant truncate on table "public"."campaign_image_records" to "service_role";

grant update on table "public"."campaign_image_records" to "service_role";


  create policy "Give users authenticated access to folder 1052rgn_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'campaign_images'::text));



  create policy "Give users authenticated access to folder 1052rgn_1"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'campaign_images'::text));



  create policy "Give users authenticated access to folder 1052rgn_2"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'campaign_images'::text));



  create policy "Give users authenticated access to folder 1052rgn_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'campaign_images'::text));



