
  create table "public"."competition_metadata" (
    "competition_id" bigint generated by default as identity not null,
    "start_date" date not null,
    "end_date" date
      );


alter table "public"."competition_metadata" enable row level security;

alter table "public"."campaigns" add column "competition_id" bigint;

CREATE UNIQUE INDEX competition_metadata_pkey ON public.competition_metadata USING btree (competition_id);

alter table "public"."competition_metadata" add constraint "competition_metadata_pkey" PRIMARY KEY using index "competition_metadata_pkey";

alter table "public"."campaigns" add constraint "campaigns_competition_id_fkey" FOREIGN KEY (competition_id) REFERENCES public.competition_metadata(competition_id) not valid;

alter table "public"."campaigns" validate constraint "campaigns_competition_id_fkey";

grant delete on table "public"."competition_metadata" to "anon";

grant insert on table "public"."competition_metadata" to "anon";

grant references on table "public"."competition_metadata" to "anon";

grant select on table "public"."competition_metadata" to "anon";

grant trigger on table "public"."competition_metadata" to "anon";

grant truncate on table "public"."competition_metadata" to "anon";

grant update on table "public"."competition_metadata" to "anon";

grant delete on table "public"."competition_metadata" to "authenticated";

grant insert on table "public"."competition_metadata" to "authenticated";

grant references on table "public"."competition_metadata" to "authenticated";

grant select on table "public"."competition_metadata" to "authenticated";

grant trigger on table "public"."competition_metadata" to "authenticated";

grant truncate on table "public"."competition_metadata" to "authenticated";

grant update on table "public"."competition_metadata" to "authenticated";

grant delete on table "public"."competition_metadata" to "service_role";

grant insert on table "public"."competition_metadata" to "service_role";

grant references on table "public"."competition_metadata" to "service_role";

grant select on table "public"."competition_metadata" to "service_role";

grant trigger on table "public"."competition_metadata" to "service_role";

grant truncate on table "public"."competition_metadata" to "service_role";

grant update on table "public"."competition_metadata" to "service_role";


