drop extension if exists "pg_net";

create type "public"."existence" as enum ('new', 'existing');

create type "public"."role" as enum ('campaign_member', 'campaign_leader');

create type "public"."status" as enum ('submitted_under_review', 'approved', 'not_approved');


  create table "public"."answers" (
    "answer_id" bigint generated by default as identity not null,
    "campaign_id" bigint,
    "question_id" bigint,
    "pre_ai_answer" text,
    "ai_answer" text,
    "final_answer" text
      );


alter table "public"."answers" enable row level security;


  create table "public"."campaign_members" (
    "user_id" bigint generated by default as identity not null,
    "campaign_id" bigint,
    "role" public.role
      );


alter table "public"."campaign_members" enable row level security;


  create table "public"."campaigns" (
    "campaign_id" bigint generated by default as identity not null,
    "name" text,
    "givebutterlink" text,
    "status" public.status,
    "date_created" text,
    "street" text,
    "city" text,
    "state" text,
    "country" text,
    "zipcode" text,
    "project_category" text,
    "project_beneficiaries" text[],
    "existence" public.existence,
    "impact" bigint,
    "size" bigint,
    "goal" bigint,
    "ein" text,
    "mailing_street" text,
    "mailing_city" text,
    "mailing_state" text,
    "mailing_country" text,
    "mailing_zipcode" text
      );


alter table "public"."campaigns" enable row level security;


  create table "public"."questions" (
    "question_id" bigint generated by default as identity not null,
    "question" text,
    "is_active" boolean default false,
    "question_number" bigint
      );


alter table "public"."questions" enable row level security;


  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text default ''::text,
    "middle_name" text default ''::text,
    "last_name" text default ''::text,
    "email" text default ''::text,
    "phone_number" text default ''::text,
    "is_admin" boolean not null default false
      );


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX campaign_members_pkey ON public.campaign_members USING btree (user_id);

CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (campaign_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."campaign_members" add constraint "campaign_members_pkey" PRIMARY KEY using index "campaign_members_pkey";

alter table "public"."campaigns" add constraint "campaigns_pkey" PRIMARY KEY using index "campaigns_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

grant delete on table "public"."answers" to "anon";

grant insert on table "public"."answers" to "anon";

grant references on table "public"."answers" to "anon";

grant select on table "public"."answers" to "anon";

grant trigger on table "public"."answers" to "anon";

grant truncate on table "public"."answers" to "anon";

grant update on table "public"."answers" to "anon";

grant delete on table "public"."answers" to "authenticated";

grant insert on table "public"."answers" to "authenticated";

grant references on table "public"."answers" to "authenticated";

grant select on table "public"."answers" to "authenticated";

grant trigger on table "public"."answers" to "authenticated";

grant truncate on table "public"."answers" to "authenticated";

grant update on table "public"."answers" to "authenticated";

grant delete on table "public"."answers" to "service_role";

grant insert on table "public"."answers" to "service_role";

grant references on table "public"."answers" to "service_role";

grant select on table "public"."answers" to "service_role";

grant trigger on table "public"."answers" to "service_role";

grant truncate on table "public"."answers" to "service_role";

grant update on table "public"."answers" to "service_role";

grant delete on table "public"."campaign_members" to "anon";

grant insert on table "public"."campaign_members" to "anon";

grant references on table "public"."campaign_members" to "anon";

grant select on table "public"."campaign_members" to "anon";

grant trigger on table "public"."campaign_members" to "anon";

grant truncate on table "public"."campaign_members" to "anon";

grant update on table "public"."campaign_members" to "anon";

grant delete on table "public"."campaign_members" to "authenticated";

grant insert on table "public"."campaign_members" to "authenticated";

grant references on table "public"."campaign_members" to "authenticated";

grant select on table "public"."campaign_members" to "authenticated";

grant trigger on table "public"."campaign_members" to "authenticated";

grant truncate on table "public"."campaign_members" to "authenticated";

grant update on table "public"."campaign_members" to "authenticated";

grant delete on table "public"."campaign_members" to "service_role";

grant insert on table "public"."campaign_members" to "service_role";

grant references on table "public"."campaign_members" to "service_role";

grant select on table "public"."campaign_members" to "service_role";

grant trigger on table "public"."campaign_members" to "service_role";

grant truncate on table "public"."campaign_members" to "service_role";

grant update on table "public"."campaign_members" to "service_role";

grant delete on table "public"."campaigns" to "anon";

grant insert on table "public"."campaigns" to "anon";

grant references on table "public"."campaigns" to "anon";

grant select on table "public"."campaigns" to "anon";

grant trigger on table "public"."campaigns" to "anon";

grant truncate on table "public"."campaigns" to "anon";

grant update on table "public"."campaigns" to "anon";

grant delete on table "public"."campaigns" to "authenticated";

grant insert on table "public"."campaigns" to "authenticated";

grant references on table "public"."campaigns" to "authenticated";

grant select on table "public"."campaigns" to "authenticated";

grant trigger on table "public"."campaigns" to "authenticated";

grant truncate on table "public"."campaigns" to "authenticated";

grant update on table "public"."campaigns" to "authenticated";

grant delete on table "public"."campaigns" to "service_role";

grant insert on table "public"."campaigns" to "service_role";

grant references on table "public"."campaigns" to "service_role";

grant select on table "public"."campaigns" to "service_role";

grant trigger on table "public"."campaigns" to "service_role";

grant truncate on table "public"."campaigns" to "service_role";

grant update on table "public"."campaigns" to "service_role";

grant delete on table "public"."questions" to "anon";

grant insert on table "public"."questions" to "anon";

grant references on table "public"."questions" to "anon";

grant select on table "public"."questions" to "anon";

grant trigger on table "public"."questions" to "anon";

grant truncate on table "public"."questions" to "anon";

grant update on table "public"."questions" to "anon";

grant delete on table "public"."questions" to "authenticated";

grant insert on table "public"."questions" to "authenticated";

grant references on table "public"."questions" to "authenticated";

grant select on table "public"."questions" to "authenticated";

grant trigger on table "public"."questions" to "authenticated";

grant truncate on table "public"."questions" to "authenticated";

grant update on table "public"."questions" to "authenticated";

grant delete on table "public"."questions" to "service_role";

grant insert on table "public"."questions" to "service_role";

grant references on table "public"."questions" to "service_role";

grant select on table "public"."questions" to "service_role";

grant trigger on table "public"."questions" to "service_role";

grant truncate on table "public"."questions" to "service_role";

grant update on table "public"."questions" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


